name: 2. Build APK

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Clean everything
        run: |
         flutter clean
         rm -rf ~/.gradle/caches
         rm -rf ~/.gradle/wrapper
         
      - name: Checkout Repo
        uses: actions/checkout@v4

      - name: Setup Java
        uses: actions/setup-java@v4
        with:
          distribution: 'zulu'
          java-version: '17'
          cache: 'gradle'
      - name: Force JAVA_HOME for Gradle
        run: echo "JAVA_HOME=$JAVA_HOME" >> $GITHUB_ENV

      - name: Cache Flutter SDK
        id: cache-flutter
        uses: actions/cache@v4
        with:
          path: /opt/hostedtoolcache/flutter
          key: flutter-3.27.4-ubuntu-latest

      - name: Setup Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.27.4'

      # Decode keystore from secrets
      - name: Decode Keystore
        run: |
          echo "${{ secrets.KEYSTORE_BASE64 }}" | base64 --decode > android/app/upload-keystore.jks

      # Create key.properties for Gradle signing
      - name: Create key.properties
        run: |
          echo "storePassword=${{ secrets.STORE_PASSWORD }}" > android/key.properties
          echo "keyPassword=${{ secrets.KEY_PASSWORD }}" >> android/key.properties
          echo "keyAlias=${{ secrets.KEY_ALIAS }}" >> android/key.properties
          echo "storeFile=alle-keystore.jks" >> android/key.properties

      - name: Get Dependencies
        run: flutter pub get

      - name: Analyze Project
        run: flutter analyze

      # Build with automatic versionCode
      - name: Build APK
        run: flutter build apk --release --build-number=${{ github.run_number }}

      - name: Upload APK
        uses: actions/upload-artifact@v4
        with:
          name: Alle_
          path: build/app/outputs/flutter-apk/app-release.apk
